# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{revo-lockdown}
  s.version = "1.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Stone", "Revo Pty. Ltd."]
  s.date = %q{2010-03-02}
  s.description = %q{Restrict access to your controller actions.  Supports basic model level restrictions as well}
  s.email = %q{andy@stonean.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".gitignore",
     "README.txt",
     "Rakefile",
     "lib/lockdown.rb",
     "lib/lockdown/context.rb",
     "lib/lockdown/errors.rb",
     "lib/lockdown/frameworks/rails.rb",
     "lib/lockdown/frameworks/rails/controller.rb",
     "lib/lockdown/frameworks/rails/view.rb",
     "lib/lockdown/helper.rb",
     "lib/lockdown/permission.rb",
     "lib/lockdown/references.rb",
     "lib/lockdown/rspec_helper.rb",
     "lib/lockdown/rules.rb",
     "lib/lockdown/session.rb",
     "lib/lockdown/system.rb",
     "revo-lockdown-1.7.0.gem",
     "revo-lockdown.gemspec",
     "spec/lockdown/context_spec.rb",
     "spec/lockdown/frameworks/rails/controller_spec.rb",
     "spec/lockdown/frameworks/rails/view_spec.rb",
     "spec/lockdown/frameworks/rails_spec.rb",
     "spec/lockdown/permission_spec.rb",
     "spec/lockdown/rspec_helper_spec.rb",
     "spec/lockdown/rules_spec.rb",
     "spec/lockdown/session_spec.rb",
     "spec/lockdown/system_spec.rb",
     "spec/lockdown_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://stonean.com/wiki/lockdown}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{lockdown}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Authorization system for Rails 2.x}
  s.test_files = [
    "spec/lockdown_spec.rb",
     "spec/spec_helper.rb",
     "spec/lockdown/system_spec.rb",
     "spec/lockdown/context_spec.rb",
     "spec/lockdown/permission_spec.rb",
     "spec/lockdown/session_spec.rb",
     "spec/lockdown/rspec_helper_spec.rb",
     "spec/lockdown/rules_spec.rb",
     "spec/lockdown/frameworks/rails_spec.rb",
     "spec/lockdown/frameworks/rails/view_spec.rb",
     "spec/lockdown/frameworks/rails/controller_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

